idf_component_register(
    SRCS 
        "main.c" 
        "sensors.c" 
        "power.c" 
        "display.c"
        "touch.c"
        "wifi.c"
        "sdcard.c"
    INCLUDE_DIRS 
        "."
    REQUIRES 
        driver 
        freertos 
        esp_lcd 
        lvgl 
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        esp_http_server
        mdns
        esp_timer
        fatfs
        sdmmc
        vfs
    PRIV_REQUIRES 
        esp_lcd_gc9a01 
        log 
        spi_flash
    EMBED_FILES
        "web/index.html"
        "web/main.css"
        "web/main.js"
        "web/files.html"
        "web/files.css"
        "web/files.js"
        "web/fh_technikum_wien_logo.png"
)